services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: ["celery", "-A", "your_celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
    cap_add:
      - NET_ADMIN
    volumes:
      - /host/path/to/dumps:/container/path/to/dumps
    network_mode: "host"

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - redis
