services:
  redis:
    image: redis:latest
    container_name: NAD_redis

  celery:
    image: NAD/server
    container_name: NAD_celery
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
    volumes:
      - ./server/cicflow-dumps:/app/cicflow-dumps
      - ./server:/app

  flask:
    image: NAD/server
    container_name: NAD_flask
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    depends_on:
      - redis
    volumes:
      - ./server:/app
